name: Deploy
on:
  repository_dispatch:
    types: [deploy-command]

jobs:
  Explore-Event:
    runs-on: ubuntu-latest
    steps:
    - name: View payload attributes
      uses: actions/github-script@v6
      with:
       script: console.log(context.payload)
    - name: View client_payload attributes
      uses: actions/github-script@v6
      with:
       script: console.log(context.payload.client_payload)
    - name: View GitHub payload attributes
      uses: actions/github-script@v6
      with:
       script: console.log(context.payload.client_payload.github.payload)
