name: Python Unit Test

on: [pull_request,workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: View world
      run: |
        pwd
        id
        ls -al
    - name: Docker stuff
      run: |
        docker version
        docker images
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Unit test the code
      run: |
        python -m unittest
