name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  Explore-Event:
    runs-on: ubuntu-latest
    steps:
    - name: View context attributes
      uses: actions/github-script@v6
      with:
       script: console.log(context)

  Slash-Command-Dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          commands: |
            deploy
